.SILENT:
include Makefile.const

# ---------------------------------------------------------------------------
# Build options
#
#   RUNTIME=quickjs   (default) JavaScript runtime: runs main.js / athena.ini.
#   RUNTIME=native    No script engine. The application provides
#                     int athena_main(int argc, char **argv), passed with
#                     APP_SRCS=... or linked later against `make lib`.
#   DEBUG=1           Debug build (bin/<name>_debug.elf, not stripped).
#   EE_SIO=1          printf over EE SIO.
#
# The module set comes from Makefile.modules, generated by
#   node tools/modules.js configure --modules=a,b,c | --defaults | --all
# ---------------------------------------------------------------------------

RUNTIME ?= quickjs
DEBUG ?= 0
EE_SIO ?= 0
APP_SRCS ?=

ifeq ($(filter $(RUNTIME),quickjs native),)
  $(error RUNTIME must be 'quickjs' or 'native' (got '$(RUNTIME)'))
endif

ifeq ($(wildcard Makefile.modules),)
  $(error Makefile.modules not found. Run: node tools/modules.js configure --defaults)
endif
include Makefile.modules

define HEADER

==================================================
           AthenaEnv ($(RUNTIME) runtime)
==================================================

endef
export HEADER

EE_EXT = .elf

ifeq ($(RUNTIME),quickjs)
  EE_BIN_PREF ?= athena
else
  EE_BIN_PREF ?= athena_native
endif

BUILD_TAG = $(RUNTIME)
ifeq ($(DEBUG),1)
  EE_BIN_PREF := $(EE_BIN_PREF)_debug
  BUILD_TAG := $(BUILD_TAG)-debug
endif
ifneq ($(EE_SIO), 0)
  EE_BIN_PREF := $(EE_BIN_PREF)_eesio
  BUILD_TAG := $(BUILD_TAG)-eesio
endif

# One object tree per configuration, so switching RUNTIME/DEBUG never mixes objects.
EE_OBJ_DIR := $(EE_OBJ_DIR)$(BUILD_TAG)/

ATHENA_ELF = $(EE_BIN_DIR)$(EE_BIN_PREF)$(EE_EXT)
ATHENA_PKD = $(EE_BIN_DIR)$(EE_BIN_PREF)_pkd$(EE_EXT)
ATHENA_LIB = lib/libathena.a

# ---------------------------------------------------------------------------
# Flags
# ---------------------------------------------------------------------------

# Grouped so module libraries may depend on each other in any order.
EE_LIBS = -L$(PS2SDK)/ports/lib -Wl,--start-group $(MODULE_LIBS) -lpatches -lfileXio -ldebug -lz -Wl,--end-group

EE_INCS += -I$(PS2SDK)/ports/include -Isrc/core/include -Isrc/readini/include $(MODULE_INCS)

EE_CFLAGS += -Wall -fpermissive -DCONFIG_VERSION=\"$(shell cat VERSION 2>/dev/null || echo 2.0.0)\" \
             -D__TM_GMTOFF=tm_gmtoff -DPATH_MAX=256 -DPS2 -MMD -MP

# Dead-code removal: each function/object gets its own section so the linker
# drops whatever the selected modules do not reference. Disabled when a module
# needs the full symbol table at runtime (erl), since ERL modules may call
# functions the binary itself never uses.
EE_CFLAGS += -ffunction-sections -fdata-sections
ifneq ($(MODULE_EXPORT_SYMBOLS),1)
  ATHENA_LDFLAGS += -Wl,--gc-sections
endif

# Main thread stack (the PS2SDK linkfile default is 128 KB). QuickJS takes
# about 0.4 KB of it per JavaScript call (JS_CallInternal), so 512 KB allows
# roughly 1200 levels of recursion before a catchable "stack overflow".
MAIN_STACK_SIZE ?= 0x80000
ATHENA_LDFLAGS += -Wl,--defsym,_stack_size=$(MAIN_STACK_SIZE)

ifeq ($(DEBUG),1)
  EE_CFLAGS += -DDEBUG
endif

ifneq ($(EE_SIO), 0)
  EE_CFLAGS += -D__EESIO_PRINTF
  EE_LIBS += -lsiocookie
endif

# ---------------------------------------------------------------------------
# Objects
# ---------------------------------------------------------------------------

CORE = core/boot.o core/memory.o core/ee_tools.o core/iop_manager.o core/iop_registry.o \
       core/module_registry.o core/strUtils.o core/excepHandler.o core/exceptions.o \
       core/sioprintf.o core/athena_math.o core/posix.o

INI_READER = readini/src/readini.o

# IOP drivers every build needs for file I/O (see core/iop_registry.c). Boot
# device drivers (memcard, usbmass, cdrom) and the rest are embedded by their
# modules (MODULE_EMBED).
CORE_IRX = iomanx.o filexio.o

# Modules may ship C sources, assembly (.s) and prebuilt VU microprograms (.vsm).
src_to_obj = $(patsubst src/%.s,%.o,$(patsubst src/%.vsm,%.o,$(patsubst src/%.c,%.o,$(1))))

MODULE_OBJS = $(call src_to_obj,$(MODULE_SRCS))
MODULE_EMBED_OBJS = $(MODULE_EMBED:%=%.o)

ifeq ($(RUNTIME),quickjs)
  JS_CORE = quickjs/cutils.o quickjs/libbf.o quickjs/libregexp.o quickjs/libunicode.o \
            quickjs/realpath.o quickjs/quickjs.o quickjs/quickjs-libc.o
  RUNTIME_OBJS = runtime/quickjs/main.o runtime/quickjs/ath_env.o runtime/quickjs/ath_gil.o \
                 runtime/quickjs/ath_output.o \
                 $(JS_CORE) $(call src_to_obj,$(MODULE_JS_SRCS)) $(MODULE_JS_EMBED:%=%.o)
  EE_INCS += -Isrc/runtime/quickjs/include -Isrc/quickjs
  EE_CFLAGS += -DATHENA_RUNTIME_QUICKJS -DCONFIG_BIGNUM
else
  RUNTIME_OBJS = runtime/native/main.o
  EE_CFLAGS += -DATHENA_RUNTIME_NATIVE
endif

LIB_OBJS = $(CORE) $(INI_READER) $(RUNTIME_OBJS) $(MODULE_OBJS) $(CORE_IRX) $(MODULE_EMBED_OBJS)
LIB_OBJS := $(LIB_OBJS:%=$(EE_OBJ_DIR)%)

# Application sources (native runtime) may live anywhere in the tree.
APP_OBJS = $(patsubst %.c,$(EE_OBJ_DIR)app/%.o,$(APP_SRCS))

EE_OBJS = $(LIB_OBJS) $(APP_OBJS)

MODULE_EMBED_BUILD_DIRS = $(strip $(foreach e,$(MODULE_EMBED),$(MODULE_EMBED_BUILD_$(e))))

# ---------------------------------------------------------------------------
# Targets
# ---------------------------------------------------------------------------

.PHONY: all debug lib sdk adp clean rebuild

comma := ,

LINK = $(EE_CC) -T$(EE_LINKFILE) $(EE_OPTFLAGS) $(EE_LDFLAGS) $(ATHENA_LDFLAGS) $(EXTRA_LDFLAGS)

all: $(EE_OBJS)
	@mkdir -p $(EE_BIN_DIR)
ifeq ($(MODULE_EXPORT_SYMBOLS),1)
	# Two-pass link: the first binary provides the symbol list for exports.c.
	$(LINK) -o $(EE_BIN_DIR)tmp.elf $(EE_OBJS) $(EE_LIBS) src/modules/erl/native/dummy-exports.c
	sh ./build-exports.sh
	$(EE_CXX) -T$(EE_LINKFILE) $(EE_OPTFLAGS) $(EE_LDFLAGS) $(ATHENA_LDFLAGS) $(EXTRA_LDFLAGS) \
		-fpermissive -Wno-write-strings -o $(ATHENA_ELF) $(EE_OBJS) $(EE_LIBS) $(EE_SRC_DIR)exports.c
	rm -f $(EE_BIN_DIR)tmp.elf
else
	$(LINK) -o $(ATHENA_ELF) $(EE_OBJS) $(EE_LIBS)
endif
	@echo "$$HEADER"
	echo "Built $(ATHENA_ELF) [modules: $(MODULE_IDS)]"
ifneq ($(DEBUG),1)
	$(EE_STRIP) $(ATHENA_ELF)
	ps2-packer $(ATHENA_ELF) $(ATHENA_PKD) > /dev/null 2>&1 || true
endif

debug:
	$(MAKE) DEBUG=1 all

# Static library with the core, the selected modules and the chosen runtime.
# With RUNTIME=native, link it with objects that define athena_main():
#   $(EE_CC) -T$(EE_LINKFILE) app.o -Llib -lathena $(ATHENA_LIBS)
# lib/athena.mk carries the include paths and libraries to use.
lib: $(LIB_OBJS)
	@mkdir -p $(dir $(ATHENA_LIB))
	rm -f $(ATHENA_LIB)
	$(EE_AR) rcs $(ATHENA_LIB) $(LIB_OBJS)
	printf 'ATHENA_RUNTIME = %s\nATHENA_MODULES = %s\nATHENA_INCS = %s\nATHENA_LIBS = %s\nATHENA_LDFLAGS = %s\n' \
		'$(RUNTIME)' '$(MODULE_IDS)' '$(strip $(filter-out -I. -I$(PS2SDK)/ee/include -I$(PS2SDK)/common/include,$(filter -I%,$(EE_INCS))))' '$(strip $(EE_LIBS))' '$(strip $(ATHENA_LDFLAGS))' \
		| sed 's|-Isrc/|-I$$(ATHENA_ROOT)/src/|g' > lib/athena.mk
	echo "Built $(ATHENA_LIB) [$(RUNTIME) runtime, modules: $(MODULE_IDS)]"

# Self-contained SDK for C applications (RUNTIME=native): the library, the
# public headers of the core and of the selected modules, a makefile fragment
# and the samples, packed as dist/athena-sdk.tar.gz. Headers are namespaced
# (<athena/...>), so all include/ trees merge into one directory.
SDK_DIR = dist/athena-sdk
SDK_INCLUDE_DIRS = src/core/include src/generated $(patsubst -I%,%,$(filter -Isrc/modules/%/include,$(MODULE_INCS)))

sdk: lib
ifneq ($(RUNTIME),native)
	$(error make sdk requires RUNTIME=native)
endif
	rm -rf $(SDK_DIR) dist/athena-sdk.tar.gz
	mkdir -p $(SDK_DIR)/lib $(SDK_DIR)/include
	cp $(ATHENA_LIB) $(SDK_DIR)/lib/
	for dir in $(SDK_INCLUDE_DIRS); do cp -R $$dir/. $(SDK_DIR)/include/; done
	find $(SDK_DIR)/include -type f ! -name '*.h' -delete
	rm -rf $(SDK_DIR)/include/athena/js # QuickJS binding headers
	cp -R samples $(SDK_DIR)/samples
	printf '%s\n' \
		'# AthenaEnv SDK ($(RUNTIME) runtime). Modules: $(MODULE_IDS)' \
		'ATHENA_SDK ?= $$(dir $$(lastword $$(MAKEFILE_LIST)))' \
		'ATHENA_INCS = -I$$(ATHENA_SDK)/include $(strip $(filter-out -I. -Isrc/% -I$(PS2SDK)/ee/include -I$(PS2SDK)/common/include,$(filter -I%,$(EE_INCS))))' \
		'ATHENA_LIBS = -L$$(ATHENA_SDK)/lib $(subst -Wl$(comma)--start-group,-Wl$(comma)--start-group -lathena,$(strip $(EE_LIBS)))' \
		'ATHENA_LDFLAGS = $(strip $(ATHENA_LDFLAGS))' > $(SDK_DIR)/athena.mk
	tar -czf dist/athena-sdk.tar.gz -C dist athena-sdk
	echo "Built dist/athena-sdk.tar.gz [modules: $(MODULE_IDS)]"

# Sound effects: converts every .wav under ADP_DIR into the .adp Sound.Sfx
# loads, when the .adp is missing or older than the .wav; `name.loop.wav`
# makes a looping `name.loop.adp`. The converter is built with the host
# compiler (tools/wav2adp.js does the same where Node is available):
#   make adp ADP_DIR=bin/sfx
HOST_CC ?= gcc
WAV2ADP = tools/wav2adp/wav2adp
ADP_WAVS = $(if $(ADP_DIR),$(shell find $(ADP_DIR) -type f -name '*.wav'))

$(WAV2ADP): tools/wav2adp/wav2adp.c
	@echo HOSTCC - $<
	$(HOST_CC) -std=c99 -O2 -Wall -o $@ $< -lm

%.loop.adp: %.loop.wav | $(WAV2ADP)
	./$(WAV2ADP) -L $< $@

%.adp: %.wav | $(WAV2ADP)
	./$(WAV2ADP) $< $@

adp: $(WAV2ADP) $(ADP_WAVS:.wav=.adp)
ifeq ($(ADP_DIR),)
	$(error make adp needs ADP_DIR=<folder with .wav files>)
endif
	echo "Sound effects up to date in $(ADP_DIR) ($(words $(ADP_WAVS)) .wav files)"

clean:
	echo Cleaning executables...
	rm -f $(EE_BIN_DIR)*.elf $(WAV2ADP)
	rm -rf $(EE_OBJ_DIR:$(BUILD_TAG)/=) $(EE_EMBED_DIR) lib dist
	rm -f $(EE_SRC_DIR)exports.c
	$(foreach dir,$(MODULE_EMBED_BUILD_DIRS),$(MAKE) -C $(dir) clean;)

rebuild: clean all

include $(PS2SDK)/samples/Makefile.pref
include $(PS2SDK)/samples/Makefile.eeglobal
include Makefile.embed

$(EE_EMBED_DIR):
	@mkdir -p $@

$(EE_OBJ_DIR)%.o: $(EE_SRC_DIR)%.c
	@echo CC - $<
	@mkdir -p $(@D)
	$(EE_CC) $(EE_CFLAGS) $(EE_INCS) -c $< -o $@

$(EE_OBJ_DIR)%.o: $(EE_SRC_DIR)%.s
	@echo AS - $<
	@mkdir -p $(@D)
	$(EE_AS) $(EE_ASFLAGS) $(EE_INCS) $< -o $@

$(EE_OBJ_DIR)%.o: $(EE_SRC_DIR)%.S
	@echo AS - $<
	@mkdir -p $(@D)
	$(EE_CC) $(EE_CFLAGS) $(EE_INCS) -c $< -o $@

# Prebuilt VU microprograms; vcl is not part of the toolchain image.
$(EE_OBJ_DIR)%.o: $(EE_SRC_DIR)%.vsm
	@echo DVP - $<
	@mkdir -p $(@D)
	$(EE_DVP) $< -o $@

$(EE_OBJ_DIR)%.o: $(EE_EMBED_DIR)%.c
	@echo BIN2C - $<
	@mkdir -p $(@D)
	$(EE_CC) $(EE_CFLAGS) $(EE_INCS) -c $< -o $@

$(EE_OBJ_DIR)app/%.o: %.c
	@echo CC - $<
	@mkdir -p $(@D)
	$(EE_CC) $(EE_CFLAGS) $(EE_INCS) -c $< -o $@

-include $(EE_OBJS:.o=.d)
