#-------------------- Embedded IOP Modules ------------------------#
$(EE_EMBED_DIR)iomanx.c: $(PS2SDK)/iop/irx/iomanX.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ iomanX_irx

$(EE_EMBED_DIR)filexio.c: $(PS2SDK)/iop/irx/fileXio.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ fileXio_irx

$(EE_EMBED_DIR)sio2man.c: $(PS2SDK)/iop/irx/sio2man.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ sio2man_irx

$(EE_EMBED_DIR)mcman.c: $(PS2SDK)/iop/irx/mcman.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ mcman_irx

$(EE_EMBED_DIR)mcserv.c: $(PS2SDK)/iop/irx/mcserv.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ mcserv_irx

$(EE_EMBED_DIR)padman.c: $(PS2SDK)/iop/irx/padman.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ padman_irx

$(EE_EMBED_DIR)usbd.c: $(PS2SDK)/iop/irx/usbd.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ usbd_irx

$(EE_EMBED_DIR)bdm.c: $(PS2SDK)/iop/irx/bdm.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ bdm_irx

$(EE_EMBED_DIR)bdmfs_fatfs.c: $(PS2SDK)/iop/irx/bdmfs_fatfs.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ bdmfs_fatfs_irx

$(EE_EMBED_DIR)usbmass_bd.c: $(PS2SDK)/iop/irx/usbmass_bd.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ usbmass_bd_irx

$(EE_EMBED_DIR)cdfs.c: $(PS2SDK)/iop/irx/cdfs.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ cdfs_irx

$(EE_EMBED_DIR)poweroff.c: $(PS2SDK)/iop/irx/poweroff.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ poweroff_irx

iop_modules/freeram/freeram.irx: iop_modules/freeram
	$(MAKE) -C $<

$(EE_EMBED_DIR)freeram.c: iop_modules/freeram/freeram.irx | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ freeram_irx

#-------------------- Embedded EE Modules ------------------------#

ee_modules/loader/loader.elf: ee_modules/loader
	$(MAKE) -C $<

$(EE_EMBED_DIR)loader_elf.c: ee_modules/loader/loader.elf | $(EE_EMBED_DIR)
	$(BIN2S) $< $@ loader_elf
